### ISSUE TITLE
missing texture : mossy birch item shelf

### ISSUE THREAD

**Issue by kxrebear** [MehVahdJukaar/supp_squared#47]
![Image](https://github.com/user-attachments/assets/f156dd03-dd38-412f-9371-d4f6f269469f)

![Image](https://github.com/user-attachments/assets/482eddec-bc00-4c32-839b-861e1e084ba9)

the other shelves work, only the birch shows up like this.

**Comment by MehVahdJukaar** [comment]
version?

**Comment by MehVahdJukaar** [comment]
should be fixed maybe

**Comment by ZEROX7** [comment]
version is 1.21.1 and iam on neoforge and everhing is up to date, still broken for all non vanilla version

**Comment by MehVahdJukaar** [comment]
Still broken for all non vanilla? Didn't you say it was just an error of ones with birch in name? Screenshot above has some modded ones that seem ok

**Comment by kxrebear** [comment]
ok so after the update all of them ended up showing up with missing textures, not sure why since it worked before with only birch being missing, however, i’ve noticed that when i add a mod with new wood, supplementaries also adds a wood variant (shelf) that the other mod wouldnt add. here’s an example in the photo: i didn’t have hoary item shelf before i added bountiful fares mod, but after it shows up, with it being a missing textures (this is specifically for the shelves) 

![Image](https://github.com/user-attachments/assets/8f6d06b5-25e2-46b9-9ae5-7c329c5669a0)

![Image](https://github.com/user-attachments/assets/93beba94-f03f-43b8-8b24-4396fc8de4e1)

i’m on 1.21.1 , fabric btw 

edit: i downgraded from the most recent update and all the shelves show up normally, it’s only the birch one. it could just be an inference with a resource pack or mod but to my knowledge i don't think i've downloaded any mods that change the birch wood, only a resource pack. 

![Image](https://github.com/user-attachments/assets/5a83eaf9-5711-4e44-a41a-8c5d7ce781a6)

**Comment by equal-l2** [comment]
~~Any progress on the issue? I encountered this on 1.2.14 on NeoForge 1.12.1.
Every shelves except normal "Item Shelf" lack their texture.~~
Nevermind, it resolved once I updated Supplementaries to the latest.
